name: Bicep Deploy Storage Infra

on:
  pull_request:
    paths: ["infra/**"]
  push:
    branches: ["main"]
    paths: ["infra/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: es_cloud_resume_resources
  TEMPLATE_FILE: infra/storage_deploy.bicep

concurrency:
  group: infra-prod
  cancel-in-progress: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Bicep
        run: az bicep build --file "${{ env.TEMPLATE_FILE }}"

  whatif:
    if: github.event_name == 'pull_request'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: What-If
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group what-if \
              --resource-group "${{ env.RESOURCE_GROUP }}" \
              --template-file "${{ env.TEMPLATE_FILE }}" \
              --parameters "@${{ env.PARAM_FILE }}"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest
    # Add this later if you want approvals:
    # environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy (Incremental)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
              --name "gh-${{ github.run_id }}" \
              --resource-group "${{ env.RESOURCE_GROUP }}" \
              --template-file "${{ env.TEMPLATE_FILE }}" \
              --mode Incremental
